### ISSUE TITLE
PLZ ANTI BYTE 1950 DISCONNECT 

### ISSUE THREAD

**Issue by xSypherr** [abbe/vrcondom#4]
PLZ ANTI BYTE 1950 DISCONNECT 
PLZ ANTI BYTE 1950 DISCONNECT 
PLZ ANTI BYTE 1950 DISCONNECT 
PLZ ANTI BYTE 1950 DISCONNECT 
PLZ ANTI BYTE 1950 DISCONNECT

**Comment by jerk** [comment]
Shut up 😐
